global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gin-boilerplate'
    static_configs:
      - targets: ['localhost:2024']  # Adjust to your app's port
        labels:
          environment: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']